### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by Silentssss** [burchim/EfficientConformer#20]
Hi!, That is my ERROR and my para, Can you tell me how to fix it? Iam very confused!
`python main.py --config_file configs/EfficientConformerCTCSmall.json --prepare_dataset --create_tokenizer`

![image](https://user-images.githubusercontent.com/108161275/218035449-24a26bf4-65e7-4145-abf1-c8a1a8dbbc40.png)

**Comment by burchim** [comment]
Hi,

TimeMasking's forward function now requires the batch dimension to process spectrograms.

Including the batch dimension should fix the issue:
`x[b:b+1, :, :x_len[b]] = torchaudio.transforms.TimeMasking(time_mask_param=T).forward(x[b:b+1, :, :x_len[b]])`

instead of:
`x[b, :, :x_len[b]] = torchaudio.transforms.TimeMasking(time_mask_param=T).forward(x[b, :, :x_len[b]])`

**Comment by Silentssss** [comment]
> Hi,
> 
> TimeMasking's forward function now requires the batch dimension to process spectrograms.
> 
> Including the batch dimension should fix the issue: `x[b:b+1, :, :x_len[b]] = torchaudio.transforms.TimeMasking(time_mask_param=T).forward(x[b:b+1, :, :x_len[b]])`
> 
> instead of: `x[b, :, :x_len[b]] = torchaudio.transforms.TimeMasking(time_mask_param=T).forward(x[b, :, :x_len[b]])`

Thanks! It works for me!
![image](https://user-images.githubusercontent.com/108161275/218231691-2eb67660-108d-4933-aa8e-b8ce13424afb.png)
