### ISSUE TITLE
Doubt for training on custom data

### ISSUE THREAD

**Issue by debasish-mihup** [burchim/EfficientConformer#4]
My input training data is already in encoded phoneme form. Where each phoneme is represented by a single character. I can convert my training data in same format as librispeech data. Is there anything else I need to be careful about during the training phase?

I am seeing sentencepiece tokenizer use, do I need to create tokenizer for my training data too? Also, is this tokenizer model used by conformer or LM?

**Comment by burchim** [comment]
Hi,

You shouldn't have any problem if you converted all your data to the LibriSpeech text format. 

Using the pretrained tokenizer should be okay as this is a byte pair encoding one, you will not have out of vocab errors. The same tokenizer must be used for both LM and conformer, otherwise models outputs will not match during decoding.
